apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: |-
         {
          "protected": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ",
          "encrypted_key": "gaw8HzkhSO_KgE_OuwVwNgzDVawVWg3WMQh0bw6yJKIWDu2MEeKrPJI9CMc5D9qVV7F-LgsYpaAzH9EIn1OPvQ5YY7pv8PfTPTA5SIQNPrhOkUvbga2XVJSnnKQMP8rcE6kwFLnd0YKup5jygXVZK9LuX1QvA5-oUPxkJTsFqcMB2uolc5vKfKWj-VdE9RLwdbcDxFs4vFLBOTHeqR5LR4kunlVgeYuzO54b3jweR8AyI1b_1pTlS3vzDz9RERpqjT95r8Hpic4RVid28OjQp3X_Wccl80LCMWrxDtq1_RPuWGttktcs_upmAlHD_DDi4xEGzM1byi9a1wb2Ns-wiwUxfM4f_jObxkLTTS0EL7n_mkxcqew-QyQGdaway2RR98N8CfMw6W2vfoy0BaP-mXUzZFSYlArJQlcKM7nguJGkeLja1wlVWbCsWgY4nqMxznrgvShK-4MssvWTGRYQ9TaEEX53Qb5M6W8b80PW--w8buSJKv4coNkFwhBz-Vu_ulQ8m8Qm-7cyaTd_snUBFVg42XJwLZtg_tdFkRWGfRiMqquGVZ6FOwCyXL-ywNOcdTshsk5YK-4aWnCSiOjavQlQuuOACUz8_dNpeQi_eFlDent88Chk90w4X0gaTgcXv8TlaPubpxnohgzYFdJIO6SwrJTtnRGlfU1mMdD6vJE",
          "iv": "CeivIv6oSXPBiu7rbxnBrQ",
          "ciphertext": "d6VJq05qxxCSQaX_VZTVeQ",
          "tag": "HTMKcE3sWBxryfb9jIVsew"
          }
