apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: |-
   {
    "protected": "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0",
    "encrypted_key": "UeKCSPNHzvL00uYmneBE5n5Fw9qj5Nnenx419hbkJXnD83MfmecruY03DXRtxLxMMYDNMEY1gMflYTf8G4gSHafpoqJcoBPcBbpcQaLBQNPlNrUSnvMxsIrriYgz8m8Q9zSW3KMnzxB5Rf5vjozUz8UvHgRjsZ2LnvV0PfiZrpkyIfxX2AvpZ4UKUl-r1ug_oc1hOQmILX1BgOt2VebL7UjdAmjN4uyEfyD9A_KZmreNcHLIFtc_oJnjlPjxZO163cEjMcN9D5ZadFfjlFhfP7cZuyB83UjkbLaLXYkLnzmr1QPhqaFxKTZ0-qCGlCfG6uphBCs1dDRx-V-5oNwVeb-2VdXlNqPb9J10b4nUr81fj_nDTkCtoY9iiKr6K1f270wphqCFULBqbnvS8pP1N3HcaswnasgIFSaMTj_L0k1cVXlUHv_syAXTWSzswX6XSF4ysGI8RHhjnTjIyC61VsCeXjPR78_VopNFxjx6KecNQHnApjRZO9-SxFDpHos4k2-d93zfanMEDjfrUFy4e_8FP9ZUL8z5yAx1lkoSYg9EvJzl7YIzAgzVZLmd_QazAcHaq4aQqsOYPRf1v3RDUBn3RmiNuwDqyhJMyKuwBGcX-fvty_QWnhj6zZXacIAg_E-5I-7kiksPdnxaBmxmShW9hT06jocigj5wFIhfljg",
    "iv": "wBxsgeYaFRsqWmWZbEfiPA",
    "ciphertext": "52xqFzcQaV-LvcyWigZpRA",
    "tag": "7m83r75eYCkAMeNOL52rpA"
   }
